/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 92
   Tile set      : C:\Users\tatos\Documents\Trabajo\Videojuegos\Jams\ZGB Jam18\ZGB-template-master\res\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map2Width 20
#define map2Height 92
#define map2Bank 0

extern unsigned char map2[];

/* End of MAP2.H */
