/*

 SPLASHMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\tatos\Documents\Trabajo\Videojuegos\Jams\ZGB Jam18\ZGB-template-master\res\tilesSplash.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splashMapWidth 20
#define splashMapHeight 18
#define splashMapBank 0

extern unsigned char splashMap[];

/* End of SPLASHMAP.H */
